name: .NET

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release -v n
      - name: Test
        if: github.event_name == 'pull_request'
        run: |
          dotnet test -c Release --no-build -v n /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
          mv Interpreter.Tests/coverage.cobertura.xml coverage.cobertura.xml
      - name: Code Coverage Summary Report
        if: github.event_name == 'pull_request'
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 20
          fail_below_threshold: true
          show_class_names: true
          show_missing: true
          link_missing_lines: true
          show_branch: true
          only_changed_files: true
  
  create-release:
    name: Create release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  upload-release-assets:
    name: Upload release assets
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: create-release
    strategy:
      matrix:
        config: 
          - os: ubuntu-latest
            rid: linux-x64
            filename: Interpreter
          - os: macos-latest
            rid: osx-x64
            filename: Interpreter
          - os: windows-latest
            rid: win-x64
            filename: Interpreter.exe
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Publish
        run: |
          mkdir output
          dotnet publish -c Release -r ${{ matrix.config.rid }} -p:PublishSingleFile=true -p:DebugType=embedded --self-contained false -o ./output
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: interpreter-${{ matrix.config.rid }}
          file: ./output/${{ matrix.config.filename }}
